name: Deploy to Hosting

on:
  push:
    branches:
      - main  # Change to your deployment branch if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Pull latest changes from Git
      run: ssh ynjnlkew@103.140.90.100 "cd fajargarage.api.alvinsetyapranata.my.id && git pull origin main"
